# Generated by Django 6.0.3 on 2026-04-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_business'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
